name: Deploy Hydrogen App to Shopify Oxygen
on:
  push:
    branches:
      - main  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Shopify Oxygen
        run: shopify deploy oxygen  --path  ./build
        env:
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
        SHOP:  tinkertown42.myshopify.com
    
